version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=images
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=images
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - AWS_S3_BUCKET=tex-public-images
      - AWS_S3_ACCESS=AKIAVN7NE4ORMSI2QINR
      - AWS_S3_SECRET=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